apiVersion: v1
kind: Service
metadata:
  labels:
    name: read-verticle
    visualize: "true"
    cluster01: "true"
  name: read-verticle
spec:
  ports:
    - port: 5701
      targetPort: 5701
      name: read-verticle
  selector:
    name: read-verticle
