apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: read-verticle
    visualize: "true"
  name: read-verticle-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: read-verticle
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests/read-verticle:vertxHazelPatchLabel01
        name: read-verticle
        ports:
        - name: read-verticle
          containerPort: 5701
