apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: write-verticle
    visualize: "true"
  name: write-verticle-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: write-verticle
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests/write-verticle:vertxHazelPatchLabel01
        name: write-verticle
        ports:
        - name: write-verticle
          containerPort: 5701
